parameters:
    maven_form.embedded_form.class:   Maven\Bundle\FormBundle\Form\Type\ContactRequestType
    maven_form.datagrid.helper.class: Maven\Bundle\FormBundle\Datagrid\ContactRequestDatagridHelper

services:
    maven_form.embedded_form:
        class: %maven_form.embedded_form.class%
        arguments:
            - @request_stack
        tags:
            - { name: oro_embedded_form, label: maven.form.embedded_form.label }
            - { name: form.type, alias: maven_form_contact_request }

    maven_form.contact_request.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "maven_form_contact_request"
            - "maven_form_contact_request"
            - null
            - { dataChannelField : true }
