layout:
    actions:
        - '@setBlockTheme':
            themes: 'MavenFormBundle:layouts:embedded_default/oro_embedded_form_submit/maven_form.html.twig'
        - '@setOption':
            id:          embedded_form
            optionName:  preferred_fields
            optionValue: [fullName, phoneOrEmail]
#        - '@setOption':
#            id:          embedded_form
#            optionName:  groups
#            optionValue:
#                contact:
#                    title:   Contact Information
#                    default: true
        - '@move':
            id:          embedded_form_submit
            parentId:    embedded_form
            siblingId:   'embedded_form:group_contact'

    conditions:
        '@eq':
            - $context.embedded_form_type
            - 'maven_form.embedded_form'
